# Contains different utility checks for Pull Requests.
name: PR Utils

# Only apply to PRs which target 'main' branch.
on:
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Run linter
        uses: abinnovision/actions@run-commitlint-v1
  dependabot:
    name: "Dependabot automations"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: abinnovision/actions@triage-dependabot-pr-v1
